### ISSUE TITLE
bug: altsysrq.c can not compile in Fedora 25 (incompatible-pointer-types)

### ISSUE THREAD

**Issue by sztsian** [kdump-test/kdump-test#34]
altsysrq.c compile error, even if I pass -Wno-error to the makefile

make -C /lib/modules/4.8.10-300.fc25.x86_64/build M=/home/zsun/tmp/kdump-test/crash-altsysrq-c/altsysrq modules -Wno-error
make[1]: Entering directory '/usr/src/kernels/4.8.10-300.fc25.x86_64'
  CC [M]  /home/zsun/tmp/kdump-test/crash-altsysrq-c/altsysrq/altsysrq.o
/home/zsun/tmp/kdump-test/crash-altsysrq-c/altsysrq/altsysrq.c:94:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
>         .write = altsysrq_write_proc,
>                  ^~~~~~~~~~~~~~~~~~~
/home/zsun/tmp/kdump-test/crash-altsysrq-c/altsysrq/altsysrq.c:94:18: note: (near initialization for ‘altsysrq_proc_fops.write’)
cc1: some warnings being treated as errors
scripts/Makefile.build:295: recipe for target '/home/zsun/tmp/kdump-test/crash-altsysrq-c/altsysrq/altsysrq.o' failed
make[2]: *** [/home/zsun/tmp/kdump-test/crash-altsysrq-c/altsysrq/altsysrq.o] Error 1
Makefile:1475: recipe for target '_module_/home/zsun/tmp/kdump-test/crash-altsysrq-c/altsysrq' failed
make[1]: *** [_module_/home/zsun/tmp/kdump-test/crash-altsysrq-c/altsysrq] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.8.10-300.fc25.x86_64'
Makefile:6: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by linuxqiao** [comment]
take, will fix asap!

**Comment by sztsian** [comment]
I am closing these in bulks as we are not using Github issue to track tasks any more. If you have other questions, feel free to reopen.
