### ISSUE TITLE
task: add basic crash check on vmcore to kdump tests.

### ISSUE THREAD

**Issue by emmawu** [kdump-test/kdump-test#35]
Please add basic crash check to vmcore generated by kdump tests.
Make sure no warn or error message.

* add a lib method to do the basic crash check on vmcore
* add crash check to existing tests

**Comment by linuxqiao** [comment]
we have exist function "check_vmcore_file". i will add new test case "analyse-core-crash".

**Comment by sztsian** [comment]
I am closing these in bulks as we are not using Github issue to track tasks any more. If you have other questions, feel free to reopen.
