### ISSUE TITLE
bug: taskout.log on s390x contains invalid characters

### ISSUE THREAD

**Issue by emmawu** [kdump-test/kdump-test#37]
Take 'crash-altsysrq-c' as an example. 
Attached the taskout.log of crash-altsysrq-c test on x86_64 and s390x: 
- x86_64: [taskout.x86_64.log.txt](https://github.com/kdump-test/kdump-test/files/630127/taskout.x86_64.log.txt)
- s390x: [taskout.s390x.log.txt](https://github.com/kdump-test/kdump-test/files/630128/taskout.s390x.log.txt)

**Comment by sztsian** [comment]
I do not think this is a problem.
IIRC this is the color control sequence which applies the color to show on console. While in serial console this is not accepted.

**Comment by sztsian** [comment]
I am closing these in bulks as we are not using Github issue to track tasks any more. If you have other questions, feel free to reopen.
