### ISSUE TITLE
task: add test to clean up files

### ISSUE THREAD

**Issue by emmawu** [kdump-test/kdump-test#38]
This is not a test actually.  But we need to set it up as a separate a task which can be added/removed easily to a beaker recipe. 
This task should clean up all temp files/vmcore from previous runs, so we can run other kdump/crash tests on same machine without interfering the test data.

**Another issue**, currently we restore kdump.conf after each test in ready_to_exit() of lib/log.sh
`cp "${K_BACKUP_DIR}"/kdump.conf /etc/kdump.conf`

We should remove this step from ready_to_exit(), and implement it in a separate cleanup test if needed.

**Comment by sztsian** [comment]
I am closing these in bulks as we are not using Github issue to track tasks any more. If you have other questions, feel free to reopen.
